compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: configs/deepspeed/zero2.json
  zero3_init_flag: false
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

distributed_type: FSDP
fsdp_config:
  use_fsdp: true
  fsdp_sharding_strategy: 1
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen2DecoderLayer
  fsdp_ignored_modules: [vision_tower, mm_projector]